# Generated by Django 3.0.7 on 2020-06-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0003_post_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publication_date',
            new_name='post_date',
        ),
    ]
